apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: to4awooy8-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d946e0e6e5.t5rs.p3.openshiftapps.com/rhtap/rhtap-qe:04c9922a8d8d2ce4c908f1d652cb1edd0fd0f537@sha256:c330d8fa831e8623feedd26fb4570f2c9b1df0ce618dbf263d6e213baeed38ac
          name: container-image
